### ISSUE TITLE
Feature request: Make player walk faster on the paths than on dirt.

### ISSUE THREAD

**Issue by adamryczkowski** [minetest-mods/mypaths#3]
As in title.

**Comment by sofar** [comment]
While I'm somewhat sympathetic to the idea, it shouldn't be added in this mod:

- this mod is mostly cosmetic
- it may require engine support
- it would benefit other mods and projects if it could be installed as a separate mod

**Comment by DonBatman** [comment]
I like the idea but I agree with sofar. I might consider making a mod that allows that but I am not able to do that now. Maybe in the future.

Thanks for the idea!

**Comment by adamryczkowski** [comment]
@DonBatman - well, I could. I am a professional programmer and I have a son, that just got interested in programming (he is 8) and he loves MineTest. Unfortunately we don't have experience with Minetest LUA API. If you could give me a few pointers, we would be able to make such mod.

**Comment by DonBatman** [comment]
I am more than willing to help. I think if you start here.
 http://dev.minetest.net/Main_Page

And rubenwardys modding book is also helpful.
 http://donbatman.github.io/moddingbook.html

Any questions you may have can be asked in irc or on the forum. I suggest that you ask on the forum since there are many people that can help.

**Comment by sofar** [comment]
I would suggest starting a new mod that just accomplishes this. Loop over all players in globalstep, and if they are standing on a certain node, modify their speed parameters.

**Comment by DonBatman** [comment]
I have decided to close this issue since I am not going to add it. 

@adamryczkowski - Feel free to fork thismod if you want and add the features you would like.
